USE [master]
GO

/****** Object:  Database [Курсовая]    Script Date: 9/28/2020 7:49:50 PM ******/
CREATE DATABASE [Курсовая]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Курсовая', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Курсовая.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Курсовая_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Курсовая_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Курсовая].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Курсовая] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Курсовая] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Курсовая] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Курсовая] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Курсовая] SET ARITHABORT OFF 
GO

ALTER DATABASE [Курсовая] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Курсовая] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Курсовая] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Курсовая] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Курсовая] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Курсовая] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Курсовая] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Курсовая] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Курсовая] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Курсовая] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Курсовая] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Курсовая] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Курсовая] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Курсовая] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Курсовая] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Курсовая] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Курсовая] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Курсовая] SET RECOVERY FULL 
GO

ALTER DATABASE [Курсовая] SET  MULTI_USER 
GO

ALTER DATABASE [Курсовая] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Курсовая] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Курсовая] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Курсовая] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Курсовая] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Курсовая] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Курсовая] SET  READ_WRITE 
GO

